### ISSUE TITLE
Separate Galil objects in GUI Application

### ISSUE THREAD

**Issue by adam-smashr** [AdamCarrera/UltraHydro#4]
# Summary

The MainWindow and tabWidget class both create galil objects, rather than sharing one.

MainWindow has methods for 
* Jogging
* Scanning
* Cleanup

tabWidget has methods for 
* Toggling conection

`tabWidget.Galil()` can connect to the controller as expected. The issue arises when calling methods in MainWindow, because `MainWindow.Galil()` is not connected to any controller.

# Issue Recreation

A basic stripped down version of issue is shown below:

```python
class Galil():
    def __init__(self):
        self.connected = False

    def connect(self):
        if self.connected:
            self.connected = False
        else:
            self.connected = True
        
        print("Galil Connection Status: {0}".format(self.connected))

    def jog_motors(self):
        if self.connected:
            print("jogging motors!")
        else:
            print("connection not established")

class MainWindow():

    def __init__(self):
        self.Galil = Galil()
        self.ui_components()

    def button_connect(self):
        print("connect button clicked...")
        self.Galil.connect()
    
    def ui_components(self):
        self.tabWidgetBox = tabWidget()

class tabWidget():
    
    def __init__(self):
        self.Galil = Galil()
    
    def button_jog(self):
        print("jog button clicked...")
        self.Galil.jog_motors()


def main():
    myApp = MainWindow()

    myApp.button_connect()
    myApp.tabWidgetBox.button_jog()

if __name__ == '__main__':
    main()
```
Which outputs...

```
connect button clicked...
Galil Connection Status: True
jog button clicked...
connection not established
```

We need to find a way to have our code share one Galil object. Maybe through inheritance? Given the size of the code, I'd like to get input from the team so we can be on the same page.

**Comment by mantos92** [comment]
One of the most powerful aspects of Python is that it uses object-oriented programming (OOP), and the issue you raise is a perfect example of where OOP is extremely powerful.

Typically, although not always, you will instantiate most of your objects in your main window class. Then, whenever you want to share access to an object across multiple classes (objects), you can just do the following:

1. Create an instance of the object (Galil in this example) in the main window
2. Pass in the newly created object as an argument to the constructor of all the other classes (objects) that you would like to have access to the functions of the Galil

You're passing a reference to this object in memory, you are not making a copy of the object. So that allows as many objects as you want to have access to the Galil functions, _without_ creating multiple copies and taking lots of space in memory! You just need to be careful not to have multiple classes trying to access the hardware at the same time, that would be bad. For this you may want to implement a `QMutex()` to make sure that only one object at a time can call the motor functions.

# Code Changes

One way to share access to the Galil object is as follows:
```python
class Galil():
    def __init__(self):
        self.connected = False

    def connect(self):
        if self.connected:
            self.connected = False
        else:
            self.connected = True
        
        print("Galil Connection Status: {0}".format(self.connected))

    def jog_motors(self):
        if self.connected:
            print("jogging motors!")
        else:
            print("connection not established")

class MainWindow():

    def __init__(self):
        self.Galil = Galil()  # here is your initial instance of Galil()
        self.ui_components()

    def button_connect(self):
        print("connect button clicked...")
        self.Galil.connect()
    
    def ui_components(self):
        # pass the Galil() instance as an argument to the constructor
        # self.tabWidgetBox = tabWidget()
        self.tabWidgetBox = tabWidget(galil=self.Galil)  # make sure self.Galil exists

class tabWidget():  # note, this class definition does not inherit anything, it's on it's own!
    
    def __init__(self, galil=None):  # updated constructor to accept the galil input
        # self.Galil = Galil()
        if galil is not None:
            self.Galil = galil
        else:
            print("where's my galil!?")
    
    def button_jog(self):
        print("jog button clicked...")
        self.Galil.jog_motors()


def main():
    myApp = MainWindow()

    myApp.button_connect()
    myApp.tabWidgetBox.button_jog()

if __name__ == '__main__':
    main()
```

You'll find the output now will be:
![image](https://user-images.githubusercontent.com/52361916/109884444-f54fbd80-7c4a-11eb-8a7f-045adb070475.png)

```
connect button clicked...
Galil Connection Status: True
jog button clicked...
jogging motors!
```

Give it a try and let me know if you have any questions!

**Comment by adam-smashr** [comment]
Thanks Marc! I'm able to control the motors with the UI now. Closing the issue 👍🏽
